GET http://localhost:8000/users

###

GET http://localhost:8000/users/636b0500bed880af884e1c53

###

POST http://localhost:8000/users
Content-Type: application/json

{
    "username": "johndoe",
    "password": "2342435",
    "email": "deez@test.com"
}

###

DELETE http://localhost:8000/users/636b0500bed880af884e1c53

### 

PATCH http://localhost:8000/users/636b099207b55f3b04782b4a
Content-Type: application/json

{
    "username": "obitoppin",
    "password": "rjbarett",
    "email": "deuce@gmail.com"
}

###

GET http://localhost:8000/tracks/636c017f7a40e2ddbd4e3482
